### ISSUE TITLE
Context menus disappear when selecting an area

### ISSUE THREAD

**Issue by dieulot** [noelpush/noelpush#11]
When you enter the area selection, the moment you click to start selecting the area, Windows Explorer’s [context menu](http://image.noelshack.com/fichiers/2015/47/1447934482-untitled.png) will disappear if there was any opened, thus those context menus aren’t screenable with NoelPush (unless you triple-press and send the whole screen).

**Comment by Imperare** [comment]
We need to freeze the screen.

**Comment by dieulot** [comment]
Go for it

**Comment by Imperare** [comment]
Done
