### ISSUE TITLE
LInes on bottom and right aren’t selected

### ISSUE THREAD

**Issue by dieulot** [noelpush/noelpush#26]
When selecting an area, I selected all of my 1920×1080 first display, but I noticed [the result](http://image.noelshack.com/fichiers/2015/47/1448205420-2741-noelpush.jpeg) is only 1919×1079. It turns out the pixel lines on the bottom and the right haven’t been selected.

This also happens when I’m not taking all of one of my display, the bottom and right lines aren’t sent.

**Comment by Imperare** [comment]
Done
