### ISSUE TITLE
Get stats from update checking

### ISSUE THREAD

**Issue by dieulot** [noelpush/noelpush#29]
A request to https://www.noelpush.com/check_update should be made before calling UpdateManager.

It must be sent with the POST paramaters `current_version` and `uid`. `current_version` must be just the major number, without the trailing ".0.0".

If the request is successful, the response will be either "1" or "0". If it’s something else it might be good to log that.

If it is 1, it means there’s a new update, and UpdateManager should be called. If it’s 0, no new version, no need to call UpdateManager.

**Comment by Chocolayte** [comment]
Error 520 http://image.noelshack.com/fichiers/2015/52/1450812445-4524-noelpush.png

**Comment by dieulot** [comment]
I don’t have this problem, tested with the following PHP code:

```php
<?php
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://www.noelpush.com/check_update');
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, [
	'current_version' => '0.0',
	'uid' => '0.0',
]);

$result = curl_exec($ch);
echo $result;
```

**Comment by Imperare** [comment]
Done
